version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    CLUSTER_NAME: brain-tasks-cluster
    ECR_REPO: brain-tasks-app
    IMAGE_TAG: latest

phases:
  install:
    commands:
      - echo Installing kubectl
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.29.0/2024-01-04/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/kubectl

  pre_build:
    commands:
      - echo Logging into Amazon ECR
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo Building Docker image
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - docker tag $ECR_REPO:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

  post_build:
  commands:
    - echo "Pushing Docker image"
    - docker push $REPOSITORY_URI:$IMAGE_TAG

    - echo "Updating kubeconfig"
    - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

    - echo "Showing deployment file"
    - cat k8s/deployment.yaml

    - echo "Applying deployment"
    - kubectl apply -f k8s/deployment.yaml || true

    - echo "Applying service"
    - kubectl apply -f k8s/service.yaml || true

    - echo "Listing pods"
    - kubectl get pods

artifacts:
  files:
    - '**/*'
